/**
 * Wave 2 Task 8 — `loadPipeline` server-side sort + SORT-AWARE keyset
 * cursor (live Neon).
 *
 * Two concerns, one fixture:
 *
 *  1. ORDERING — `expires_at_desc` reverses the default `expires_at_asc`;
 *     `tier_asc` / `tier_desc` order by the Domain `TIER_BUCKETS` ordinal
 *     (via the drift-guarded `tierBucketOrdinalCaseSql`), NOT enum text,
 *     with `(expires_at, cycle_id)` as the stable tiebreak.
 *
 *  2. SORT-AWARE PAGINATION (the load-bearing correctness proof) — the
 *     keyset cursor is `(expires_at, cycle_id)` ASC-shaped by default. Under
 *     a non-default sort a plain ASC cursor generated by "Next 50" would
 *     DUP or SKIP rows: e.g. under `tier_desc`, once page 1 fills with the
 *     top tier, the next page's lower-tier rows (which sort AFTER but have
 *     SMALLER `expires_at`) fail a naive `expires_at > cursor` test and are
 *     silently dropped. SweCham has ~131 members → a single tier can exceed
 *     the 50-row page, so this is a real prod data-loss bug, not theoretical.
 *     These tests seed >50 rows spanning tiers and page across the 50-row
 *     boundary under `tier_desc` AND `expires_at_desc`, asserting NO
 *     duplicate and NO skipped cycle across the two pages, and that the
 *     concatenated order matches the active sort exactly.
 */
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { eq } from 'drizzle-orm';
import { randomUUID } from 'node:crypto';
import { db, runInTenant } from '@/lib/db';
import { members } from '@/modules/members/infrastructure/db/schema-members';
import { renewalCycles } from '@/modules/renewals/infrastructure/schema-renewal-cycles';
import {
  loadPipeline,
  makeRenewalsDeps,
  TIER_BUCKETS,
  type PipelineSort,
  type TierBucket,
} from '@/modules/renewals';
import { DEFAULT_TEST_BENEFIT_MATRIX } from '../helpers/test-benefit-matrix';
import { seedF8MembershipPlan } from '../helpers/seed-f8-plan';
import { createTestTenant, type TestTenant } from '../helpers/test-tenant';
import { createActiveTestUser, type TestUser } from '../helpers/test-users';
import { nextSeedMemberNumber } from '../helpers/seed-member-number';

interface SeedSpec {
  readonly cycleId: string;
  readonly memberId: string;
  readonly tier: TierBucket;
  /** Epoch ms; all DISTINCT so ordering never depends on the cycle_id tiebreak. */
  readonly expiresMs: number;
}

/** JS mirror of `tierBucketOrdinalCaseSql` (sentinel = tuple length for unknown). */
function tierOrd(tier: string): number {
  const i = (TIER_BUCKETS as readonly string[]).indexOf(tier);
  return i === -1 ? TIER_BUCKETS.length : i;
}

/** Comparator producing the EXPECTED cycleId sequence for a given sort. */
function expectedOrder(specs: readonly SeedSpec[], sort: PipelineSort): string[] {
  const byExpiresCycleAsc = (a: SeedSpec, b: SeedSpec): number =>
    a.expiresMs !== b.expiresMs
      ? a.expiresMs - b.expiresMs
      : a.cycleId < b.cycleId
        ? -1
        : a.cycleId > b.cycleId
          ? 1
          : 0;
  const sorted = [...specs].sort((a, b) => {
    switch (sort) {
      case 'expires_at_desc':
        return a.expiresMs !== b.expiresMs
          ? b.expiresMs - a.expiresMs
          : a.cycleId < b.cycleId
            ? 1
            : a.cycleId > b.cycleId
              ? -1
              : 0;
      case 'tier_asc': {
        const t = tierOrd(a.tier) - tierOrd(b.tier);
        return t !== 0 ? t : byExpiresCycleAsc(a, b);
      }
      case 'tier_desc': {
        const t = tierOrd(b.tier) - tierOrd(a.tier);
        return t !== 0 ? t : byExpiresCycleAsc(a, b);
      }
      case 'expires_at_asc':
      default:
        return byExpiresCycleAsc(a, b);
    }
  });
  return sorted.map((s) => s.cycleId);
}

describe('F8 loadPipeline — server-side sort + sort-aware cursor (integration)', () => {
  let tenant: TestTenant;
  let user: TestUser;
  let specs: SeedSpec[] = [];

  async function bulkSeed(t: TestTenant, all: readonly SeedSpec[]) {
    const planId = `f8-sort-${randomUUID().slice(0, 8)}`;
    await runInTenant(t.ctx, (tx) =>
      seedF8MembershipPlan(tx, {
        tenantSlug: t.ctx.slug,
        planId,
        planName: { en: 'F8 Sort Plan' },
        benefitMatrix: DEFAULT_TEST_BENEFIT_MATRIX,
        createdBy: user.userId,
      }),
    );
    await runInTenant(t.ctx, (tx) =>
      tx.insert(members).values(
        all.map((s) => ({
          tenantId: t.ctx.slug,
          memberId: s.memberId,
          memberNumber: nextSeedMemberNumber(),
          companyName: `Co ${s.tier} ${s.memberId.slice(0, 4)}`,
          country: 'TH',
          planId,
          planYear: 2026,
        })),
      ),
    );
    await runInTenant(t.ctx, (tx) =>
      tx.insert(renewalCycles).values(
        all.map((s) => ({
          tenantId: t.ctx.slug,
          cycleId: s.cycleId,
          memberId: s.memberId,
          status: 'upcoming' as const,
          periodFrom: new Date(s.expiresMs - 365 * 86_400_000),
          periodTo: new Date(s.expiresMs),
          expiresAt: new Date(s.expiresMs),
          cycleLengthMonths: 12,
          tierAtCycleStart: s.tier,
          planIdAtCycleStart: randomUUID(),
          frozenPlanPriceThb: '50000.00',
          frozenPlanTermMonths: 12,
          frozenPlanCurrency: 'THB' as const,
        })),
      ),
    );
  }

  beforeAll(async () => {
    user = await createActiveTestUser('admin');
    tenant = await createTestTenant('test');

    const now = Date.now();
    const DAY = 86_400_000;
    specs = [];
    // 55 partnership cycles (tier ordinal 4 — the TOP tier under tier_desc),
    // expiries 40..~83 days out — all inside the 90-day window, all DISTINCT.
    for (let i = 0; i < 55; i += 1) {
      specs.push({
        cycleId: randomUUID(),
        memberId: randomUUID(),
        tier: 'partnership',
        expiresMs: now + Math.round((40 + i * 0.8) * DAY),
      });
    }
    // 12 regular cycles (tier ordinal 2), expiries 5..16 days out — SMALLER
    // than EVERY partnership expiry. Under tier_desc these sort AFTER all
    // partnership rows yet carry the smallest expires_at, so a naive
    // ASC-(expires,cycle) cursor would SKIP them on page 2. This cohort is
    // the whole point of the sort-aware-cursor proof.
    for (let j = 0; j < 12; j += 1) {
      specs.push({
        cycleId: randomUUID(),
        memberId: randomUUID(),
        tier: 'regular',
        expiresMs: now + (5 + j) * DAY,
      });
    }
    await bulkSeed(tenant, specs);
  }, 120_000);

  afterAll(async () => {
    await db
      .delete(renewalCycles)
      .where(eq(renewalCycles.tenantId, tenant.ctx.slug))
      .catch(() => {});
    await tenant.cleanup().catch(() => {});
  }, 120_000);

  /** Fetch the WHOLE window in one page (limit > seed count). */
  async function fetchAll(sort: PipelineSort): Promise<string[]> {
    const deps = makeRenewalsDeps(tenant.ctx.slug);
    const result = await loadPipeline(deps, {
      tenantId: tenant.ctx.slug,
      sort,
      limit: 200,
    });
    expect(result.ok).toBe(true);
    if (!result.ok) throw new Error('loadPipeline failed');
    expect(result.value.nextCursor).toBeNull();
    return result.value.rows.map((r) => r.cycleId as string);
  }

  it('expires_at_desc is the exact reverse of the default expires_at_asc', async () => {
    const asc = await fetchAll('expires_at_asc');
    const desc = await fetchAll('expires_at_desc');
    expect(asc).toEqual(expectedOrder(specs, 'expires_at_asc'));
    expect(desc).toEqual(expectedOrder(specs, 'expires_at_desc'));
    // All expiries distinct → desc must be asc reversed.
    expect(desc).toEqual([...asc].reverse());
  });

  it('tier_desc orders by tier ordinal DESC then (expires_at, cycle_id) ASC', async () => {
    const rows = await fetchAll('tier_desc');
    expect(rows).toEqual(expectedOrder(specs, 'tier_desc'));
    // Concretely: every partnership (ord 4) precedes every regular (ord 2).
    const partnershipIds = new Set(
      specs.filter((s) => s.tier === 'partnership').map((s) => s.cycleId),
    );
    const lastPartnershipIdx = rows.reduce(
      (acc, id, idx) => (partnershipIds.has(id) ? idx : acc),
      -1,
    );
    const firstRegularIdx = rows.findIndex((id) => !partnershipIds.has(id));
    expect(lastPartnershipIdx).toBeLessThan(firstRegularIdx);
  });

  it('tier_asc orders by tier ordinal ASC then (expires_at, cycle_id) ASC', async () => {
    const rows = await fetchAll('tier_asc');
    expect(rows).toEqual(expectedOrder(specs, 'tier_asc'));
  });

  /**
   * THE sort-aware-cursor proof. Page across the 50-row boundary under
   * `tier_desc` and assert the union of the two pages is the seeded set
   * with NO duplicate and NO skip, in the correct order. A non-sort-aware
   * cursor drops the 12 small-expiry `regular` rows here.
   */
  it('tier_desc pagination across the 50-row boundary — no dup, no skip', async () => {
    const deps = makeRenewalsDeps(tenant.ctx.slug);
    const page1 = await loadPipeline(deps, {
      tenantId: tenant.ctx.slug,
      sort: 'tier_desc',
      limit: 50,
    });
    expect(page1.ok).toBe(true);
    if (!page1.ok) throw new Error('page1 failed');
    expect(page1.value.rows).toHaveLength(50);
    expect(page1.value.nextCursor).not.toBeNull();

    const page2 = await loadPipeline(deps, {
      tenantId: tenant.ctx.slug,
      sort: 'tier_desc',
      cursor: page1.value.nextCursor,
      limit: 50,
    });
    expect(page2.ok).toBe(true);
    if (!page2.ok) throw new Error('page2 failed');
    expect(page2.value.nextCursor).toBeNull();

    const combined = [
      ...page1.value.rows.map((r) => r.cycleId as string),
      ...page2.value.rows.map((r) => r.cycleId as string),
    ];
    // No duplicate.
    expect(new Set(combined).size).toBe(combined.length);
    // No skip: every seeded cycle appears exactly once.
    expect(new Set(combined)).toEqual(new Set(specs.map((s) => s.cycleId)));
    expect(combined).toHaveLength(specs.length);
    // Order across the page boundary matches the active sort exactly.
    expect(combined).toEqual(expectedOrder(specs, 'tier_desc'));
    // The specific data-loss guard: the small-expiry regular cohort survives.
    const regularIds = specs
      .filter((s) => s.tier === 'regular')
      .map((s) => s.cycleId);
    for (const id of regularIds) expect(combined).toContain(id);
  });

  it('expires_at_desc pagination across the 50-row boundary — no dup, no skip', async () => {
    const deps = makeRenewalsDeps(tenant.ctx.slug);
    const page1 = await loadPipeline(deps, {
      tenantId: tenant.ctx.slug,
      sort: 'expires_at_desc',
      limit: 50,
    });
    expect(page1.ok).toBe(true);
    if (!page1.ok) throw new Error('page1 failed');
    expect(page1.value.rows).toHaveLength(50);
    expect(page1.value.nextCursor).not.toBeNull();

    const page2 = await loadPipeline(deps, {
      tenantId: tenant.ctx.slug,
      sort: 'expires_at_desc',
      cursor: page1.value.nextCursor,
      limit: 50,
    });
    expect(page2.ok).toBe(true);
    if (!page2.ok) throw new Error('page2 failed');

    const combined = [
      ...page1.value.rows.map((r) => r.cycleId as string),
      ...page2.value.rows.map((r) => r.cycleId as string),
    ];
    expect(new Set(combined).size).toBe(combined.length);
    expect(new Set(combined)).toEqual(new Set(specs.map((s) => s.cycleId)));
    expect(combined).toEqual(expectedOrder(specs, 'expires_at_desc'));
  });
});
