/**
 * Thai postal-code → sub-district / district / province resolver.
 *
 * SERVER-ONLY. `data.json` is 367 KB (97 KB gzipped) — importing it from a
 * client component would blow the members-route bundle budget. The only
 * consumer is `/api/geo/postal/[code]`. See `SOURCE.md` for provenance.
 *
 * The data is NOT 1:1 and this function does NOT guess. Of 955 postal codes,
 * 174 map to more than one district and 8 span two provinces (13240 =
 * Ayutthaya/Lopburi). Callers get every candidate and let the admin choose.
 */
import 'server-only';
import data from './data.json';

export type PostalName = {
  readonly th: string;
  readonly en: string;
};

export type PostalCandidate = {
  readonly subDistrict: PostalName;
  readonly district: PostalName;
  readonly province: PostalName;
};

type PostalData = {
  readonly provinces: ReadonlyArray<readonly [string, string]>;
  readonly districts: ReadonlyArray<readonly [string, string, number]>;
  readonly byZip: Readonly<
    Record<string, ReadonlyArray<readonly [string, string, number]>>
  >;
};

// TS infers a wide literal shape from the JSON's actual contents
// (`string[][]`, `(string | number)[][]`) that doesn't structurally
// overlap with the narrower branded tuple types below, so a direct
// `as PostalData` is rejected (TS2352). The `unknown` hop is the
// documented escape hatch for a cast we know is sound: the JSON was
// generated by `scripts/generate-thai-postal-data.ts` into exactly
// this [th, en] / [th, en, index] shape and is pinned by
// `tests/unit/lib/thai-postal-data-integrity.test.ts`.
const POSTAL: PostalData = data as unknown as PostalData;

export const POSTAL_CODE_RE = /^\d{5}$/;

export function lookupPostalCode(code: string): readonly PostalCandidate[] {
  if (!POSTAL_CODE_RE.test(code)) return [];

  const subDistricts = POSTAL.byZip[code];
  if (!subDistricts) return [];

  const candidates: PostalCandidate[] = [];
  for (const [subTh, subEn, districtIndex] of subDistricts) {
    const district = POSTAL.districts[districtIndex];
    if (!district) continue;
    const province = POSTAL.provinces[district[2]];
    if (!province) continue;

    candidates.push({
      subDistrict: { th: subTh, en: subEn },
      district: { th: district[0], en: district[1] },
      province: { th: province[0], en: province[1] },
    });
  }
  return candidates;
}
